### ISSUE TITLE
what does "Please link the folder to the root of openwrt/lede source tree " mean?

### ISSUE THREAD

**Issue by jack338c** [maz-1/openwrt-cc-wndr4300#2]
Hi Could you tell me what the details for apply openwrt-mod?

just git clone to source folder? or copy all files of openwrt-mod to source folder?

thank you

**Comment by maz-1** [comment]
git clone or copy should be ok, but I would rather store this repository in a seperated dir and make a symbolic link to the root of lede source tree to keep a clean directory structure.

**Comment by maz-1** [comment]
By the way, as the repository is not updated for a long time, you may have to fix a lot of conflicts. Feel free to open pull requests.

**Comment by jack338c** [comment]
@maz-1 
thanks for your response 
I do use store this repository in a seperated dir and make a symbolic link to the root of lede source tree
but it have a lot of conflicts when I did make menuconfig , just like you said. I give up finnally
Now I will try again and tell you later
thank you !
Jack

**Comment by maz-1** [comment]
Now try to apply patches on lede-17.01 branch.

**Comment by jack338c** [comment]
ok I got it
thank you Maz

**Comment by jack338c** [comment]
Hi,maz
How are you doing ?
according  your instructions,Now I can apply patches on lede-17.01 branch.
here are my steps:
..soft link
..excute patch.sh
.../scripts/feeds update -a && ./scripts/feeds install -a
..select router and packages
...make -j 3
but something is wrong while compiling mentohust
Here is the logs,please pull me out of there,I have done  lots of google searchs,but did not make it yet

./configure: line 4923: syntax error near unexpected token `external'
./configure: line 4923: `AM_GNU_GETTEXT(external)'
Makefile:71: recipe for target '/home/jack/lede1701/build_dir/target-mips_24kc_musl-1.1.16/mentohust-4.0-alpha2/.configured_yyynynynyyy' failed
make[2]: *** [/home/jack/lede1701/build_dir/target-mips_24kc_musl-1.1.16/mentohust-4.0-alpha2/.configured_yyynynynyyy] Error 2
make[2]: Leaving directory '/home/jack/lede1701/feeds/extra/net/mentohust'
package/Makefile:105: recipe for target 'package/feeds/extra/mentohust/compile' failed
make[1]: *** [package/feeds/extra/mentohust/compile] Error 2
make[1]: Leaving directory '/home/jack/lede1701'
/home/jack/lede1701/include/toplevel.mk:198: recipe for target 'package/mentohust/compile' failed
make: *** [package/mentohust/compile] Error 2

Copying file po/remove-potcdate.sin
+ aclocal
configure.ac:69: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:70: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
+ autoheader
+ automake --add-missing
configure.ac:19: installing './compile'
configure.ac:6: installing './config.guess'
configure.ac:6: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './COPYING' using GNU General Public License v3 file
Makefile.am:     Consider adding the COPYING file to the version control system
Makefile.am:     for your code, to avoid questions about which license your project uses
src/Makefile.am: installing './depcomp'
+ autoconf
configure.ac:69: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:70: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
Makefile:71: recipe for target '/home/jack/370017011001/lede1701/build_dir/target-mips_24kc_musl-1.1.16/mentohust-4.0-alpha2/.configured_yyynnynnynyyy' failed



Thank you
