### ISSUE TITLE
hi,how to apply fastpatch --thank you

### ISSUE THREAD

**Issue by jack338c** [maz-1/openwrt-cc-wndr4300#3]
Could you please tell me how to apply fastpatch,thank you 

here are the logs while excuting lede-mod/patch.sh

Executing /home/jack/lede1701/lede-mod/patches/106_esfq/install.sh
patching file package/kernel/linux/modules/netsupport.mk
Hunk #1 succeeded at 740 (offset 9 lines).
Hunk #2 succeeded at 816 (offset 3 lines).
=================
Executing /home/jack/lede1701/lede-mod/patches/107_fast_path_kernel_patch/install.sh
=================
Executing /home/jack/lede1701/lede-mod/patches/108_qualcomm_hardware_nat_patch/install.sh
=================
Executing /home/jack/lede1701/lede-mod/patches/201_wndr4300-change-overlay/install.sh
patching file target/linux/ar71xx/image/legacy.mk
Hunk #1 succeeded at 281 (offset -11 lines).

**Comment by maz-1** [comment]
add this to your package dir : https://github.com/openwrt-stuff/qca/branches
choose one of the branches based on your architecture

**Comment by jack338c** [comment]
@maz-1 
Ok,I got it
thank you VERY much !

**Comment by jack338c** [comment]
@maz-1 
I find the speed is same like before even I add "kmod-fast-classifier"

Do you mean just add qca under package folder , skip 107_fast_path_kernel_patch/install.sh?
or need excute lede-mod/patch.sh again?
thanks

**Comment by jack338c** [comment]
@maz-1 
my mistake
it's faster ! beatitful!
thanks
